name: echo
description: Connection beyond Coverage
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ device-to-device mesh
  nearby_connections: ^4.3.0

  # ðŸ“ GPS
  geolocator: ^14.0.2

  # ðŸ”‹ battery
  battery_plus: ^7.0.0

  # ðŸ” permissions
  permission_handler: ^12.0.1

  # ðŸ†” device id
  uuid: ^4.2.1

  # ðŸ—º navigation
  url_launcher: ^6.2.5

  # ðŸŒ connectivity & gateway
  connectivity_plus: ^6.0.3
  http: ^1.2.0

  archive: ^3.6.1


  # ðŸ”” notifications
  flutter_local_notifications: ^17.2.2

  # ðŸ’¾ history
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ðŸ¤³ shake detection
  shake: ^2.2.0

  # ðŸ” encryption (NEW)
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # â­ for app icon
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

# â­ FIX FOR GRADLE NAMESPACE ERROR
dependency_overrides:
  sensors_plus: ^5.0.1

# â­ ICON CONFIGURATION
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
